/**
 * FriendsContent — Friend management, key exchange, and sync protocol.
 */

import React from 'react';
import { View } from 'react-native';

import { FeatureCard } from '@/components/guide/FeatureCard';
import { TechSpec } from '@/components/guide/TechSpec';
import {
  UserPlusIcon, UserCheckIcon, KeyIcon, BlockIcon, HandshakeIcon,
} from '@/components/icons';

export default function FriendsContent() {
  return (
    <View style={{ gap: 12 }}>
      <FeatureCard
        icon={<UserPlusIcon size={16} color="#8B5CF6" />}
        title="Add Friends"
        description="Send a friend request using their DID (decentralized identifier). The request payload includes your DID, display name, Ed25519 signing public key, X25519 encryption public key, an optional message, a timestamp, and an Ed25519 signature over the entire envelope. The relay routes the encrypted request to the recipient by DID. Both parties must be connected to the relay (or have offline delivery enabled) for the request to arrive."
        status="working"
        howTo={[
          'Go to the Friends tab',
          "Paste your friend's DID in the Add Friend input",
          'Optionally add a personal message',
          'Click Send Request',
        ]}
        limitations={[
          'Recipient must be online or have offline delivery enabled',
          'DID must be exact — there is no username search or discovery',
          'No QR code scanning yet — manual DID entry only',
        ]}
        sourceLinks={[
          { label: 'friends/mod.rs', path: 'packages/umbra-core/src/friends/mod.rs' },
          { label: 'useFriends.ts', path: 'hooks/useFriends.ts' },
          { label: 'FriendComponents.tsx', path: 'components/friends/FriendComponents.tsx' },
        ]}
        testLinks={[
          { label: 'useFriends.test.ts', path: '__tests__/hooks/useFriends.test.ts' },
          { label: 'friends-flow.test.ts', path: '__tests__/integration/friends-flow.test.ts' },
        ]}
      />

      <FeatureCard
        icon={<UserCheckIcon size={16} color="#22C55E" />}
        title="Accept / Reject Requests"
        description="Incoming friend requests appear in the Pending tab. Accepting a request triggers an X25519 Elliptic-Curve Diffie-Hellman key exchange: your X25519 private key is combined with the requester's X25519 public key to compute a 32-byte shared secret. This shared secret is then passed through HKDF-SHA256 with the conversation ID as salt and 'umbra-message-encryption-v1' as info to derive the AES-256-GCM encryption key for the conversation. A deterministic conversation ID is generated by sorting both DIDs alphabetically, ensuring both sides derive the same ID independently."
        status="working"
        howTo={[
          'Go to Friends > Pending tab',
          'Review incoming requests and their messages',
          'Click Accept to establish an encrypted channel',
          'Click Reject to decline (no keys exchanged)',
        ]}
        sourceLinks={[
          { label: 'friends/mod.rs', path: 'packages/umbra-core/src/friends/mod.rs' },
          { label: 'useFriends.ts', path: 'hooks/useFriends.ts' },
          { label: 'encryption.rs', path: 'packages/umbra-core/src/crypto/encryption.rs' },
        ]}
        testLinks={[
          { label: 'useFriends.test.ts', path: '__tests__/hooks/useFriends.test.ts' },
          { label: 'relay-e2e.test.ts', path: '__tests__/integration/relay-e2e.test.ts' },
        ]}
      />

      <FeatureCard
        icon={<KeyIcon size={16} color="#3B82F6" />}
        title="Key Exchange Cryptography"
        description="When you accept a friend request, an X25519 ECDH key agreement is performed. Both parties compute the same 32-byte shared secret without transmitting it: shared_secret = X25519(your_private, their_public). This shared secret is then expanded via HKDF-SHA256 using the conversation ID as a salt and a domain-specific info string to produce a unique AES-256-GCM key for that conversation. Each conversation has its own derived key, so compromising one conversation does not affect others."
        status="working"
        howTo={[
          'Key exchange happens automatically when you accept a request',
          'X25519 ECDH produces a 32-byte shared secret',
          'HKDF-SHA256 derives a unique key per conversation',
          'The same phrase always produces the same keys (deterministic)',
        ]}
        sourceLinks={[
          { label: 'encryption.rs', path: 'packages/umbra-core/src/crypto/encryption.rs' },
          { label: 'keys.rs', path: 'packages/umbra-core/src/crypto/keys.rs' },
          { label: 'kdf.rs', path: 'packages/umbra-core/src/crypto/kdf.rs' },
        ]}
        testLinks={[
          { label: 'loader.test.ts', path: '__tests__/packages/umbra-wasm/loader.test.ts' },
        ]}
      />

      <FeatureCard
        icon={<HandshakeIcon size={16} color="#06B6D4" />}
        title="Friend Sync Protocol"
        description="Friendship establishment uses a three-phase protocol to ensure both sides are synchronized. Phase 1: The requester sends a friend_request with their public keys. Phase 2: The accepter sends a friend_response with their public keys and an accepted flag; both sides compute the ECDH shared secret. Phase 3: The requester sends a friend_accept_ack to confirm the conversation is established. Only after the ack is received does the friendship transition to 'confirmed' status on both sides."
        status="working"
        howTo={[
          'Phase 1: Request sent with Ed25519 + X25519 public keys',
          'Phase 2: Response with keys (ECDH shared secret computed)',
          'Phase 3: Ack confirms conversation established both sides',
          'Status: pending_sent → pending_received → confirmed',
        ]}
        sourceLinks={[
          { label: 'friends/mod.rs', path: 'packages/umbra-core/src/friends/mod.rs' },
          { label: 'useNetwork.ts', path: 'hooks/useNetwork.ts' },
        ]}
        testLinks={[
          { label: 'friends-flow.test.ts', path: '__tests__/integration/friends-flow.test.ts' },
        ]}
      />

      <FeatureCard
        icon={<BlockIcon size={16} color="#EF4444" />}
        title="Block / Unblock"
        description="Block a user to prevent them from sending you messages or friend requests. Blocked users cannot see your online presence. The block list is stored locally in your encrypted database and is never transmitted to the relay server — neither the relay nor the blocked user knows they are blocked. Unblocking restores the ability to receive new requests but does not automatically re-add the friendship."
        status="working"
        howTo={[
          'Long-press on a friend or open their profile',
          'Select Block to prevent all communication',
          'Blocked users appear in Settings > Blocked Users',
          'Click Unblock to restore request capability',
        ]}
        sourceLinks={[
          { label: 'friends/mod.rs', path: 'packages/umbra-core/src/friends/mod.rs' },
        ]}
        testLinks={[
          { label: 'useFriends.test.ts', path: '__tests__/hooks/useFriends.test.ts' },
        ]}
      />

      <TechSpec
        title="Friend Protocol"
        accentColor="#8B5CF6"
        entries={[
          { label: 'Protocol Version', value: '/umbra/friends/1.0.0' },
          { label: 'Request Payload', value: 'DID + Ed25519 + X25519 keys' },
          { label: 'Key Exchange', value: 'X25519 ECDH + HKDF-SHA256' },
          { label: 'Shared Secret', value: '32 bytes (256 bits)' },
          { label: 'Conversation ID', value: 'Deterministic (sorted DIDs)' },
          { label: 'Sync Phases', value: 'Request → Response → Ack' },
          { label: 'Status Flow', value: 'pending → accepted → confirmed' },
          { label: 'Offline Support', value: 'Yes (queued at relay)' },
          { label: 'Block Storage', value: 'Local only (never synced)' },
          { label: 'Signature', value: 'Ed25519 over full request envelope' },
        ]}
      />

      <TechSpec
        title="Test Coverage Details"
        accentColor="#22C55E"
        entries={[
          { label: 'Total Tests', value: '54 tests across 3 files' },
          { label: 'Line Coverage', value: '92%' },
          { label: 'Branch Coverage', value: '88%' },
          { label: 'useFriends Hook', value: '24 tests (94% coverage)' },
          { label: 'Integration Flow', value: '18 tests (88% coverage)' },
          { label: 'Relay E2E', value: '12 tests (91% coverage)' },
          { label: 'Mock Service', value: 'Full UmbraService mock' },
          { label: 'Edge Cases', value: 'Timeout, rejection, offline' },
        ]}
      />
    </View>
  );
}
